### ISSUE TITLE
autocorrelation failure on short chains prevents triangle plot from being made

### ISSUE THREAD

**Issue by iancze** [iancze/DiskJockey#17]
If the chain is too short to reliably calculate the autocorrelation, catch the error and plot the triangle matrix regardless.

h/t G. van der Plas

```

Autocorrelation time

Traceback (most recent call last):

  File "/home/gerrit/.julia/v0.4/DiskJockey/scripts/plot_walkers.py", line 236, in <module>

    print(autocorr.integrated_time(np.mean(chain, axis=0), axis=0))

  File "/home/gerrit/miniconda2/envs/dj/lib/python2.7/site-packages/emcee-2.2.1-py2.7.egg/emcee/autocorr.py", line 118, in integrated_time

emcee.autocorr.AutocorrError: The chain is too short to reliably estimate the autocorrelation time
```

**Comment by iancze** [comment]
Triangle is now plotted before autocorrelation is calculated.
